title: Mark to Market
author: Mark to Market
email: vatousia@tcd.ie
description: > # this means to ignore newlines until "twitter_username:"
  Market Research & Analytics

# social links
twitter_username: jekyllrb
github_username:  jekyll
rss: rss
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jekyll
# linkedin_username: jekyll
# pinterest_username: jekyll
# youtube_username: jekyll
# googleplus_username: +jekyll

# Mastodon instances
# mastodon:
# - username: jekyll
#   instance: example.com
# - username: jekyll2
#   instance: example.com

permalink: /:collection/:title

show_excerpts: false # set to true to show excerpts on the homepage

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.html

sass:
  style: compressed

# Build settings
#theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-sitemap

services:
- service: Machine Learning 
  icon: robot
  description: >
    Creation of algorithms that can learn and make predictions.
- service: Quantitative Analysis
  icon: chart-line 
  description: >
    Implementation and use of models that reduce uncertainty.
- service: Data Collection
  icon: database
  description: >
    Collection of data and creation of datasets from large databases.

collections_dir: collections

collections:
  projects:
    output: true
    permalink: /:collection/:title
  members:
  services:
    output: true
    permalink: /:collection/:title
  pages:
    output: true
    permalink: /:title

assets: /assets/

defaults:
  - scope:
      path: ""
      type: projects
    values:
      layout: page
  - scope:
      path: ""
      type: members 
    values:
      layout: page
  - scope:
      path: ""
      type: services 
    values:
      layout: page

prose:
  rooturl: 'collections'
  siteurl: 'http://mark-to-market.github.io'
  media: 'assets/media'
  metadata:
    collections/_posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "title"
      - name: "author"
        field:
          element: "text"
          label: "Author"
      - name: "img"
        field:
          element: "text"
          label: "Image"
      - name: "himg"
        field:
          element: "text"
          label: "Header Image"
      - name: "categories"
        field:
          element: "multiselect"
          label: "Select Categories"
          placeholder: "Select Categories"
          options:
            - name: "Machine Learning"
              value: "Machine Learning"
            - name: "Quantitative Analysis"
              value: "Quantitative Analysis"
            - name: "Data Collection"
              value: "Data Collection"
    collections/_projects:
      - name: "layout"
        field:
          element: "hidden"
          value: "page"
      - name: "title"
        field:
          element: "text"
          label: "title"
      - name: "img"
        field:
          element: "text"
          label: "Image"
      - name: "himg"
        field:
          element: "text"
          label: "Header Image"
      - name: "title"
        field:
          element: "text"
          label: "title"
      - name: "categories"
        field:
          element: "multiselect"
          label: "Select Categories"
          placeholder: "Select Categories"
          options:
            - name: "Machine Learning"
              value: "Machine Learning"
            - name: "Quantitative Analysis"
              value: "Quantitative Analysis"
            - name: "Data Collection"
              value: "Data Collection"
    collections/_members:
      - name: "layout"
        field:
          element: "hidden"
          value: "page"
      - name: "title"
        field:
          element: "text"
          label: "title"
      - name: "role"
        field:
          element: "text"
          label: "Role"
      - name: "img"
        field:
          element: "text"
          label: "Image"
    collections/_services:
      - name: "layout"
        field:
          element: "hidden"
          value: "page"
      - name: "title"
        field:
          element: "text"
          label: "title"
      - name: "himg"
        field:
          element: "text"
          label: "Header Image"
      - name: "icon"
        field:
          element: "text"
          label: "icon"
